version: "3.5"
services:
  server:
    image: "ags131/screeps-server"
    depends_on:
      - redis
      - mongo
    volumes:
      - $PWD:/screeps
    networks:
      - screeps-net
    ports:
      - 21025:21025

  redis:
    image: "redis:3.0.6"
    networks:
      - screeps-net
    volumes:
      - screeps-redis-db:/data
    expose:
      - 6379

  mongo:
    image: "mongo:2.6.4"
    networks:
      - screeps-net
    volumes:
      - screeps-mongo-db:/data/db
    expose:
      - 27017

networks:
  screeps-net:

volumes:
  screeps-redis-db:
  screeps-mongo-db:
